package com.jegab.persistenceEntities;
// default package
// Generated 15-sep-2017 0:05:55 by Hibernate Tools 5.2.5.Final

import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

	private int idmovimiento;
	private Producto producto;
	private TipoMovimiento tipoMovimiento;
	private String cantidad;
	private Date fecha;
	private String user;

	public Movimiento() {
	}

	public Movimiento(int idmovimiento, Producto producto, TipoMovimiento tipoMovimiento, String cantidad, Date fecha,
			String user) {
		this.idmovimiento = idmovimiento;
		this.producto = producto;
		this.tipoMovimiento = tipoMovimiento;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.user = user;
	}

	public int getIdmovimiento() {
		return this.idmovimiento;
	}

	public void setIdmovimiento(int idmovimiento) {
		this.idmovimiento = idmovimiento;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public TipoMovimiento getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(TipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
