package com.jegab.persistenceEntities;
// default package
// Generated 16-sep-2017 14:15:10 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private int idProducto;
	private Categoria categoria;
	private String nombre;
	private String descripcion;
	private String codigo;
	private double precio;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Producto() {
	}

	public Producto(int idProducto, String nombre, String descripcion, String codigo, double precio) {
		this.idProducto = idProducto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.precio = precio;
	}

	public Producto(int idProducto, Categoria categoria, String nombre, String descripcion, String codigo,
			double precio, Set<Movimiento> movimientos) {
		this.idProducto = idProducto;
		this.categoria = categoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.codigo = codigo;
		this.precio = precio;
		this.movimientos = movimientos;
	}

	public int getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(int idProducto) {
		this.idProducto = idProducto;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
