package com.jegab.persistenceEntities;

// Generated 15-sep-2017 0:05:55 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoMovimiento generated by hbm2java
 */
public class TipoMovimiento implements java.io.Serializable {

	private int idtipoMovimiento;
	private String nombre;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public TipoMovimiento() {
	}

	public TipoMovimiento(int idtipoMovimiento, String nombre) {
		this.idtipoMovimiento = idtipoMovimiento;
		this.nombre = nombre;
	}

	public TipoMovimiento(int idtipoMovimiento, String nombre, Set<Movimiento> movimientos) {
		this.idtipoMovimiento = idtipoMovimiento;
		this.nombre = nombre;
		this.movimientos = movimientos;
	}

	public int getIdtipoMovimiento() {
		return this.idtipoMovimiento;
	}

	public void setIdtipoMovimiento(int idtipoMovimiento) {
		this.idtipoMovimiento = idtipoMovimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
