package com.jegab.bean;
// default package
// Generated 15-sep-2017 0:05:55 by Hibernate Tools 5.2.5.Final

import java.util.Date;

import javax.faces.bean.ManagedBean;

/**
 * Movimiento generated by hbm2java
 */
@ManagedBean(name="movimiento")
public class BeanMovimiento implements java.io.Serializable {

	private int idmovimiento;
	private BeanProducto producto;
	private BeanTipoMovimiento tipoMovimiento;
	private String cantidad;
	private Date fecha;
	private String user;

	public BeanMovimiento() {
	}

	public BeanMovimiento(int idmovimiento, BeanProducto producto, BeanTipoMovimiento tipoMovimiento, String cantidad, Date fecha,
			String user) {
		this.idmovimiento = idmovimiento;
		this.producto = producto;
		this.tipoMovimiento = tipoMovimiento;
		this.cantidad = cantidad;
		this.fecha = fecha;
		this.user = user;
	}

	public int getIdmovimiento() {
		return this.idmovimiento;
	}

	public void setIdmovimiento(int idmovimiento) {
		this.idmovimiento = idmovimiento;
	}

	public BeanProducto getProducto() {
		return this.producto;
	}

	public void setProducto(BeanProducto producto) {
		this.producto = producto;
	}

	public BeanTipoMovimiento getTipoMovimiento() {
		return this.tipoMovimiento;
	}

	public void setTipoMovimiento(BeanTipoMovimiento tipoMovimiento) {
		this.tipoMovimiento = tipoMovimiento;
	}

	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
