package com.jegab.bean;
// default package
// Generated 15-sep-2017 0:05:55 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;

/**
 * Categoria generated by hbm2java
 */
@ManagedBean(name="categoria")
public class BeanCategoria implements java.io.Serializable {

	private int idCategoria;
	private String nombre;
	private String descripcion;
	private Set<BeanProducto> productos = new HashSet<BeanProducto>(0);

	public BeanCategoria() {
	}

	public BeanCategoria(int idCategoria, String nombre, String descripcion) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
	}

	public BeanCategoria(int idCategoria, String nombre, String descripcion, Set<BeanProducto> productos) {
		this.idCategoria = idCategoria;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.productos = productos;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set<BeanProducto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<BeanProducto> productos) {
		this.productos = productos;
	}

}
